---
title: "test1"
output: html_document  
date: "2024-02-09"
---

```{r jeu de données et skim}
library(readxl)
coffee_complet <- read_excel("coffee_analysis.csv/coffee_complet.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "text", "numeric", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "numeric", 
        "numeric", "text", "text"))
View(coffee_complet) # Mon jeu de données complet

coffee_backup <- coffee_complet #Mon backup

library(tidyverse)
coffee_complet %>% 
  filter(name != "NA") %>%
   select(name:review)-> coffee_simplified #Mon jeu de données simplifie 


# Analyse univariée -------------------------------------------------------

library(skimr)
skim(coffee_simplified)
```
```{r niveau de torréfaction}

table(coffee_simplified$roast)
barplot(table(coffee_simplified$roast))

# Le niveau de torréfaction le plus produit est de moyen-léger (medium-light), suivi par light (léger) et moyenne (medium).
```
```{r roaster}
rev(sort(table(coffee_simplified$roaster)))

# Les torréfacteurs de café le plus utilisées sont Kakalove Cafe et JBC Coffee Roasters (91 les deux), suivi de prés par Paradise Roasters (83) .
```
```{r Origin du roaster}
rev(sort(table(coffee_simplified$loc_country)))

#La majorité des torréfacteurs proviennent des États-Unis (774), Taiwan (338), Hawai'i (76) et, en mineur quantité, Guatemala (24).
```
```{r origin du café}
rev(sort(table(coffee_simplified$origin)))
# La majorité du café provienne de Éthiopie (447), suivi par la Colombie (151), Kenya (143) et Hawai'i (112).

```
```{r review_date}
table(coffee_simplified$review_date)

#Les commentaires sur le café de ce jeu de données ont été faites entre novembre 2017 et novembre 2022.
```
```{r 100gr/USD}
skim(coffee_simplified$centg_USD)

# En moyenne, le café coûte 10.47 USD / 100 grammes. Cependant, la médiane est de 6.17 USD / 100 grammes.
# Les ventes varient de 0.17 à 132.28 USD / 100 grammes.

hist(coffee_simplified$centg_USD)
# La distribution est étalée vers la droite. Il semble que la majorité de café est vendu par moins de 10 USD / 100 grammes.
# On va essayer de voir plus clair en faisant plus de barres
hist(coffee_simplified$centg_USD, breaks = 70)
# Effectivement, il y a une grand quantité de café qui est vendu par moins de 10 USD / 100 grammes.
# On observe que quelques types de café sont vendus pour plus de 100 USD / 100 grammes.
# On va jeter un coup d’œil sur ces données.

cafe_cher <- subset(coffee_simplified, centg_USD > 100)
cafe_cher

# Mama Cata Mokkita est le café le plus cher de ce jeu de données. D'origine panaméenne, il coûte 132.28 USD / 100 grammmes. Aussi, il a la ponctuation la plus haute (97).
# Dans ce nouveau jeu de données, on trouve que les cafés le plus cher viennent du Panama (2), Ecuador (2) et Éthiopie (1).
# Il faut signaler que meme si le café Esmeralda Estate Panama Geisha apparaît quatre fois, il s'agit du meme café mais avec des  évaluations qui ont été faites en temps différents. 


```
```{r rating}
skim(coffee_simplified$rating)
# En moyenne, la ponctuation est 93.24. La médiane, 93.
# Les notes vont de 10.58 a 97.
hist(coffee_simplified$rating)
# La distribution est étalée vers la gauche. C'est a dire que la majorité de café de ce jeu de données a un bon ponctuation donnée par la public. Par contre, il semble qu'aucun café est noté moins que 80.
hist(coffee_simplified$rating, breaks=70)
# Maintenant, on peut observer qu'il y a une petite quantité de café qui a la ponctuation la plus basse.
# On pourrait regarder quelles sont les plus basse.
cafe_pirenote <- subset(coffee_simplified, rating < 20)
cafe_pirenote

# Il s'agit de Salvador, un café d'origine hawaïenne, avec une note de 10.58. Malheureusement, nous n'avons pas l'info sur le prix.

# Et si nous essayons de regarder le café mieux noté?
cafe_mieuxnote <- subset(coffee_simplified, rating > 96)
cafe_mieuxnote
# On trouve entre les cafés les mieux notés, ceux qui viennent du Panama, Kenya, Ethiopie, Colombie et Hawai'i. Tous ont 97, la ponctuation la plus haute de cet échantillon. 
# On trouve aussi que les prix dans ce groupe sont variées (des 5.29 USD / 100 grammes a 132.28 USD / 100 grammes)
```


